// evanbecker-client/components/CodeEditor.vue
<script setup lang="ts">
import { ref } from 'vue'

const tabs = [
  {
    name: 'ProjectController.cs',
    language: 'csharp',
    code: `[ApiController]
[Route("api/v1/project")]
public class ProjectController : ControllerBase
{
    private readonly IUserService _userService;
    private readonly IProjectService _projectService;

    public ProjectController(IUserService userService,
       IProjectService projectService)
    {
        _userService = userService;
        _projectService = projectService;
    }

    [HttpGet]
    public async Task<IActionResult> GetAllProjects()
    {
        var projects = await _projectService.GetAllProjectsAsync();
        return Ok(projects);
    }

    ...`,
  },
  {
    name: 'Stats.cpp',
    language: 'cpp',
    code: `float UStats::ApplyStatMultiplier(const float StatValue,
    const float StatMultiplier)
{
    return StatValue * StatMultiplier + StatValue;
}

UStatsCalculated* UStats::Calculate()
{
    UStatsCalculated* Calculated = NewObject<UStatsCalculated>();

    Calculated->Vitality = Vitality * Vitality_Multiplier + Vitality;

    const float MaximumHealthInner = ExtraMaximumHealth +
        HealthPerVitality * Calculated->Vitality;

    Calculated->MaximumHealth = ApplyStatMultiplier(
        MaximumHealthInner,
        ExtraMaximumHealth_Multiplier
    );
  //...
}`,
  },
]

const activeTab = ref(tabs[0])

function lineNumbers(code: string) {
  return code.split('\n').map((_, i) => String(i + 1).padStart(2, '0'))
}

function highlightCode(code: string, language: string) {
  // Tokenize then reassemble to avoid regex collisions
  const lines = code.split('\n')
  return lines.map(line => highlightLine(line, language)).join('\n')
}

function highlightLine(line: string, language: string): string {
  // Handle full-line comments first
  const commentMatch = line.match(/^(\s*)(\/\/.*)$/)
  if (commentMatch) {
    return commentMatch[1] + '<span class="text-slate-500">' + esc(commentMatch[2]) + '</span>'
  }

  const tokens: string[] = []
  // Tokenize by strings, then words, then other chars
  const re = /("(?:[^"\\]|\\.)*")|(\b[A-Za-z_]\w*\b)|(\d+\.?\d*f?)|([^\w"]+)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(line)) !== null) {
    if (m[1]) {
      // String literal
      tokens.push('<span class="text-emerald-400">' + esc(m[1]) + '</span>')
    } else if (m[2]) {
      // Word — classify it
      tokens.push(classifyWord(m[2], language))
    } else if (m[3]) {
      // Number
      tokens.push('<span class="text-amber-300">' + esc(m[3]) + '</span>')
    } else {
      tokens.push(esc(m[4]))
    }
  }
  return tokens.join('')
}

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

const KEYWORDS = new Set([
  'public', 'private', 'readonly', 'class', 'async', 'await', 'return',
  'var', 'const', 'new', 'void', 'using', 'namespace', 'static',
  'override', 'virtual', 'abstract', 'interface', 'float', 'int',
  'string', 'bool', 'struct', 'auto',
])

const TYPES = new Set([
  'Task', 'IActionResult', 'IUserService', 'IProjectService',
  'ControllerBase', 'UStats', 'UStatsCalculated',
])

const ATTRS = new Set([
  'ApiController', 'Route', 'HttpGet',
])

function classifyWord(word: string, _lang: string): string {
  if (KEYWORDS.has(word)) return '<span class="text-[#41A5F7]">' + word + '</span>'
  if (TYPES.has(word)) return '<span class="text-emerald-300">' + word + '</span>'
  if (ATTRS.has(word)) return '<span class="text-[#2D95FC]">' + word + '</span>'
  return esc(word)
}
</script>

<template>
  <div class="relative max-w-2xl">
    <!-- Glow effect -->
    <div class="absolute inset-0 rounded-2xl bg-gradient-to-tr from-[#0C65E5]/20 via-[#2D95FC]/10 to-[#41A5F7]/20 opacity-60 blur-xl" />

    <div class="relative rounded-2xl bg-slate-900 ring-1 ring-slate-700/50 dark:bg-[#0B1120] dark:ring-slate-800">
      <!-- Title bar -->
      <div class="flex items-center gap-2 px-4 pt-4">
        <div class="flex gap-1.5">
          <div class="h-3 w-3 rounded-full bg-slate-700/50" />
          <div class="h-3 w-3 rounded-full bg-slate-700/50" />
          <div class="h-3 w-3 rounded-full bg-slate-700/50" />
        </div>
      </div>

      <!-- Tabs -->
      <div class="mt-4 flex gap-2 px-4 text-xs">
        <button
          v-for="tab in tabs"
          :key="tab.name"
          @click="activeTab = tab"
          :class="[
            'rounded-full px-3 py-1 transition',
            activeTab.name === tab.name
              ? 'bg-[#2D95FC]/20 font-medium text-[#41A5F7] ring-1 ring-[#2D95FC]/30'
              : 'text-slate-500 hover:text-slate-300',
          ]"
        >
          {{ tab.name }}
        </button>
      </div>

      <!-- Code -->
      <div class="mt-4 flex items-start overflow-x-auto px-4 pb-6 text-sm">
        <div class="select-none border-r border-slate-700/30 pr-4 font-mono text-slate-600" aria-hidden="true">
          <div v-for="num in lineNumbers(activeTab.code)" :key="num">{{ num }}</div>
        </div>
        <pre class="flex-1 overflow-x-auto pl-4 font-mono"><code class="text-slate-300" v-html="highlightCode(activeTab.code, activeTab.language)"></code></pre>
      </div>
    </div>
  </div>
</template>

// evanbecker-client/src/components/CodeEditor.tsx
'use client'

import { useEffect, useState } from 'react'
import { Fragment } from 'react'
import clsx from 'clsx'
import { Highlight, Prism } from 'prism-react-renderer'

(typeof global !== "undefined" ? global : window).Prism = Prism;
require("prismjs/components/prism-docker");

const defTabs: any[] = [
  {
    name: 'Dockerfile',
    isActive: true,
    code: `[ApiController]
[Route("api/v1/project")]
public class ProjectController : ControllerBase
{
    private readonly IUserService _userService;
    private readonly IProjectService _projectService;

    public ProjectController(IUserService userService,
       IProjectService projectService)
    {
        _userService = userService;
        _projectService = projectService;
    }
    
    [HttpGet]
    public async Task<IActionResult> GetAllProjects()
    {
        var projects = await _projectService.GetAllProjectsAsync();
        return Ok(projects);
    }

    ...`,
    codeLanguage: 'c',
  },
  {
    name: 'Stats.cpp',
    isActive: false,
    code: `float UStats::ApplyStatMultiplier(const float StatValue,
    const float StatMultiplier)
{
    return StatValue * StatMultiplier + StatValue;
}

UStatsCalculated* UStats::Calculate()
{
    UStatsCalculated* Calculated = NewObject<UStatsCalculated>();

    Calculated->Vitality = Vitality * Vitality_Multiplier + Vitality;
    
    const float MaximumHealthInner = ExtraMaximumHealth + 
        HealthPerVitality * Calculated->Vitality; 
        
    Calculated->MaximumHealth = ApplyStatMultiplier(
        MaximumHealthInner,
        ExtraMaximumHealth_Multiplier
    );
  //...
}`,
    codeLanguage: 'cpp',
  },
]

function TrafficLightsIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
    return (
      <svg aria-hidden="true" viewBox="0 0 42 10" fill="none" {...props}>
        <circle cx="5" cy="5" r="4.5" />
        <circle cx="21" cy="5" r="4.5" />
        <circle cx="37" cy="5" r="4.5" />
      </svg>
    )
  }



export function CodeEditor() {

    const [tabs, setTabs] = useState(defTabs);
    const [currentTab, setCurrentTab] = useState(defTabs[0]);

    function activateTab(tabName: string)
    {
        tabs.forEach((tab) => {
            if (tab.name == tabName)
            {
                setCurrentTab(tab);
                tab.isActive = true;
            } else tab.isActive = false;
        })
        
    }

    function CodeEditorTab(tab: any) {
        return (
        <div
            key={tab.name}
            onClick={() => activateTab(tab.name)}
            className={clsx(
            'cursor-pointer flex h-6 rounded-full',
            tab.isActive
            ? 'bg-gradient-to-r from-sky-400/30 via-sky-400 to-sky-400/30 p-px font-medium text-sky-300'
            : 'text-slate-500',
            )}
        >
            <div
                className={clsx(
                'flex items-center rounded-full px-2.5',
                tab.isActive && 'bg-slate-800',
                )}
            >
                {tab.name}
            </div>
        </div>
        )
    }
    
    return (
        <div className="max-w-max">
            <div className="absolute inset-0 rounded-2xl bg-gradient-to-tr from-sky-300 via-sky-300/70 to-blue-300 opacity-10 blur-lg" />
            <div className="absolute inset-0 rounded-2xl bg-gradient-to-tr from-sky-300 via-sky-300/70 to-blue-300 opacity-10" />
            <div className="relative rounded-2xl bg-[#0A101F]/80 ring-1 ring-white/10 backdrop-blur">
            <div className="absolute -top-px left-20 right-11 h-px bg-gradient-to-r from-sky-300/0 via-sky-300/70 to-sky-300/0" />
            <div className="absolute -bottom-px left-11 right-20 h-px bg-gradient-to-r from-blue-400/0 via-blue-400 to-blue-400/0" />
            <div className="pl-4 pt-4">
                <TrafficLightsIcon className="h-2.5 w-auto stroke-slate-500/30" />
                <div className="mt-4 flex space-x-2 text-xs">
                {tabs.map((tab) => 
                    CodeEditorTab(tab)
                )}
                </div>
                <div className="mt-6 flex items-start px-1 text-sm">
                <div
                    aria-hidden="true"
                    className="select-none border-r border-slate-300/5 pr-4 font-mono text-slate-600"
                >
                    {Array.from({
                    length: currentTab.code.split('\n').length,
                    }).map((_, index) => (
                    <Fragment key={index}>
                        {(index + 1).toString().padStart(2, '0')}
                        <br />
                    </Fragment>
                    ))}
                </div>
                <Highlight
                    code={currentTab.code}
                    language={currentTab.codeLanguage}
                    theme={{ plain: {}, styles: [] }}
                >
                    {({
                    className,
                    style,
                    tokens,
                    getLineProps,
                    getTokenProps,
                    }) => (
                    <pre
                        className={clsx(
                        className,
                        'flex overflow-x-auto pb-6 w-screen',
                        )}
                        style={style}
                    >
                        <code className="px-4">
                        {tokens.map((line, lineIndex) => (
                            <div key={lineIndex} {...getLineProps({ line })}>
                            {line.map((token, tokenIndex) => (
                                <span
                                key={tokenIndex}
                                {...getTokenProps({ token })}
                                />
                            ))}
                            </div>
                        ))}
                        </code>
                    </pre>
                    )}
                </Highlight>
                </div>
            </div>
            </div>
        </div>
    )
}
